import type {
  ApplicationRecord,
  AuditEvent,
  DomainProfile,
  JobListing,
  PromptVersion,
  ResumeComponent,
  TechnologyTimeline
} from "@/lib/types";

export const ROLE_CATALOG = [
  "Java Developer",
  "Java Backend Engineer",
  "Java Full Stack Developer",
  "Spring Boot Developer",
  "C Developer",
  "C++ Developer",
  "Embedded C Developer",
  "Systems Engineer (C/C++)",
  "Go Developer",
  "Golang Backend Engineer",
  "Python Developer",
  "Python Backend Developer",
  "Django Developer",
  "Flask Developer",
  "Node.js Developer",
  "TypeScript Developer",
  "JavaScript Developer",
  "Angular Developer",
  "React Developer",
  "Vue.js Developer",
  "Frontend Engineer",
  "UI Engineer",
  "Web Developer",
  "Full Stack Developer",
  "MERN Stack Developer",
  "MEAN Stack Developer",
  "AWS Cloud Engineer",
  "AWS DevOps Engineer",
  "AWS Solutions Architect",
  "AWS Data Engineer",
  "Azure Cloud Engineer",
  "Azure DevOps Engineer",
  "Azure Data Engineer",
  "Azure Solutions Architect",
  "GCP Cloud Engineer",
  "GCP Data Engineer",
  "Cloud Security Engineer",
  "Data Analyst",
  "Business Analyst (Data)",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "Data Engineer",
  "Big Data Engineer",
  "Analytics Engineer",
  "BI Developer",
  "Tableau Developer",
  "Power BI Developer",
  "SQL Developer",
  "Database Engineer",
  "Cybersecurity Engineer",
  "Security Analyst",
  "SOC Analyst",
  "Penetration Tester",
  "Ethical Hacker",
  "Security Architect",
  "Application Security Engineer",
  "Network Security Engineer",
  "IAM Engineer",
  "Network Engineer",
  "Network Administrator",
  "Network Architect",
  "Systems Engineer",
  "Systems Administrator",
  "Linux Engineer",
  "Windows Engineer",
  "Infrastructure Engineer",
  "NOC Engineer",
  "DevOps Engineer",
  "Site Reliability Engineer (SRE)",
  "Kubernetes Engineer",
  "Docker Engineer",
  "CI/CD Engineer",
  "Build Engineer",
  "Release Engineer",
  "Platform Engineer",
  "Automation Engineer",
  "Terraform Engineer",
  "COBOL Developer",
  "Mainframe Developer",
  "Mainframe Engineer",
  "z/OS System Programmer",
  "CICS Developer",
  "IMS Developer",
  "JCL Developer",
  "AS400 Developer",
  "RPG Developer",
  "Mainframe Support Engineer",
  ".NET Developer",
  "C# Developer",
  "ASP.NET Developer",
  ".NET Core Engineer",
  "SharePoint Developer",
  "Dynamics 365 Developer",
  "Power Platform Developer",
  "SAP ABAP Developer",
  "SAP FICO Consultant",
  "SAP MM Consultant",
  "SAP SD Consultant",
  "SAP PP Consultant",
  "SAP HCM Consultant",
  "SAP Basis Administrator",
  "SAP S/4HANA Consultant",
  "Oracle Developer",
  "Oracle DBA",
  "Oracle Functional Consultant",
  "Oracle Cloud Engineer",
  "Oracle HCM Consultant",
  "Oracle Financials Consultant",
  "ServiceNow Developer",
  "ServiceNow Administrator",
  "ServiceNow Consultant",
  "ServiceNow ITSM Specialist",
  "Workday Consultant",
  "Workday HCM Consultant",
  "Workday Financials Consultant",
  "Workday Integration Developer",
  "Salesforce Developer",
  "Salesforce Administrator",
  "Salesforce Consultant",
  "Salesforce Architect",
  "Android Developer",
  "iOS Developer",
  "Swift Developer",
  "Kotlin Developer",
  "Flutter Developer",
  "React Native Developer",
  "NoSQL Engineer",
  "MongoDB Developer",
  "Cassandra Engineer",
  "Snowflake Engineer",
  "Data Warehouse Engineer",
  "QA Engineer",
  "Software Tester",
  "Automation Test Engineer",
  "Selenium Engineer",
  "Performance Test Engineer",
  "SDET",
  "Integration Developer",
  "API Developer",
  "MuleSoft Developer",
  "Kafka Engineer",
  "Middleware Engineer",
  "Blockchain Developer",
  "Web3 Engineer",
  "Smart Contract Developer",
  "AR/VR Developer",
  "IoT Engineer",
  "Robotics Engineer",
  "Computer Vision Engineer",
  "NLP Engineer",
  "MLOps Engineer",
  "LLM Engineer",
  "HPC Engineer",
  "Low Latency Engineer",
  "Quant Developer",
  "Graphics Engineer",
  "Game Developer",
  "IT Support Engineer",
  "Help Desk Technician",
  "Desktop Support Engineer",
  "Technical Support Engineer",
  "Field Support Engineer",
  "Solutions Architect",
  "Enterprise Architect",
  "Technical Architect",
  "Engineering Manager",
  "IT Manager",
  "Program Manager",
  "Product Manager",
  "Selenium Automation Engineer",
  "Selenium Test Engineer",
  "Selenium WebDriver Engineer",
  "Cypress Automation Engineer",
  "Playwright Automation Engineer",
  "Playwright Test Engineer",
  "Puppeteer Automation Engineer",
  "Tricentis Tosca Automation Engineer",
  "Tosca Test Engineer",
  "Tosca Automation Specialist",
  "UFT (QTP) Test Engineer",
  "Micro Focus UFT Automation Engineer",
  "TestComplete Automation Engineer",
  "JMeter Performance Engineer",
  "LoadRunner Performance Engineer",
  "Gatling Performance Engineer",
  "Postman API Test Engineer",
  "REST Assured Automation Engineer",
  "API Automation Engineer",
  "SOAP UI Test Engineer",
  "Appium Automation Engineer",
  "Mobile Test Engineer",
  "Mobile Automation Engineer",
  "Cucumber Automation Engineer",
  "SpecFlow Automation Engineer",
  "Behavior Driven Development (BDD) Engineer",
  "QA Automation Architect",
  "Test Framework Engineer",
  "Continuous Testing Engineer"
];

export const SUPPORTED_DOMAINS = [
  "Banking",
  "Financial Services",
  "Insurance",
  "Healthcare",
  "Hospital Systems",
  "Retail",
  "Ecommerce",
  "Manufacturing",
  "Telecom",
  "Oil and Gas",
  "Aerospace",
  "Automotive",
  "Pharmaceuticals",
  "Construction",
  "Government",
  "Education",
  "Hospitality",
  "Logistics",
  "Transportation",
  "Utilities",
  "Technology",
  "Media",
  "Supply Chain"
];

export const DOMAIN_PROFILES: DomainProfile[] = [
  {
    name: "Banking",
    dataTypes: ["accounts", "payments", "transactions", "fraud alerts", "risk scores", "ledger events"],
    systems: ["core banking", "payment rails", "fraud monitoring", "risk reporting", "customer onboarding"],
    compliance: ["SOX", "PCI DSS", "GLBA", "KYC", "AML"],
    prioritySignals: ["payments", "ledger", "fraud", "risk", "KYC", "AML", "banking"],
    generationRules: ["Prioritize governance, lineage, auditability, reconciliations, and controlled releases."]
  },
  {
    name: "Healthcare",
    dataTypes: ["claims", "members", "providers", "eligibility", "clinical records", "encounters"],
    systems: ["claims platforms", "provider portals", "member eligibility", "clinical integrations", "care management"],
    compliance: ["HIPAA", "HITECH", "PHI"],
    prioritySignals: ["claims", "member", "provider", "HIPAA", "EHR", "eligibility"],
    generationRules: ["Use HIPAA-aware language and avoid unsupported patient outcome metrics."]
  },
  {
    name: "Retail",
    dataTypes: ["orders", "pricing", "inventory", "promotions", "customer profiles", "store transactions"],
    systems: ["order management", "pricing engines", "store operations", "catalog services", "loyalty platforms"],
    compliance: ["PCI DSS", "CCPA"],
    prioritySignals: ["orders", "inventory", "pricing", "store", "promotions", "retail"],
    generationRules: ["Emphasize seasonal volume, catalog consistency, inventory accuracy, and checkout reliability."]
  },
  {
    name: "Telecom",
    dataTypes: ["subscriber data", "network telemetry", "CDR", "billing events", "provisioning requests"],
    systems: ["billing", "provisioning", "network assurance", "customer care", "usage analytics"],
    compliance: ["CPNI", "GDPR", "PCI DSS"],
    prioritySignals: ["subscriber", "network", "CDR", "provisioning", "billing", "telecom"],
    generationRules: ["Prefer event streaming, usage reconciliation, customer account, and network reliability context."]
  },
  {
    name: "Insurance",
    dataTypes: ["policies", "claims", "premiums", "underwriting rules", "broker submissions"],
    systems: ["claims processing", "policy administration", "underwriting", "billing", "agent portals"],
    compliance: ["NAIC", "SOC2", "PII"],
    prioritySignals: ["claims", "policy", "underwriting", "premium", "insurance"],
    generationRules: ["Tie work to claims throughput, policy accuracy, and underwriting decision support."]
  },
  {
    name: "Government",
    dataTypes: ["citizen records", "permits", "licenses", "case files", "program eligibility"],
    systems: ["citizen services", "case management", "permitting", "licensing", "records management"],
    compliance: ["FedRAMP", "FISMA", "Section 508"],
    prioritySignals: ["citizen", "permit", "licensing", "case management", "federal", "state"],
    generationRules: ["Use accessibility, auditability, records retention, and eligibility workflow language."]
  },
  {
    name: "Manufacturing",
    dataTypes: ["production orders", "plant telemetry", "supplier records", "inventory", "quality checks"],
    systems: ["MES", "ERP", "quality management", "plant operations", "supply planning"],
    compliance: ["ISO 9001", "SOX"],
    prioritySignals: ["plant", "production", "supplier", "MES", "manufacturing"],
    generationRules: ["Anchor bullets in production planning, quality, supplier, and plant system realities."]
  },
  {
    name: "Technology",
    dataTypes: ["usage events", "accounts", "subscriptions", "feature telemetry", "support cases"],
    systems: ["SaaS platforms", "developer portals", "billing services", "observability", "identity systems"],
    compliance: ["SOC2", "GDPR", "CCPA"],
    prioritySignals: ["SaaS", "platform", "API", "usage", "tenant", "subscription"],
    generationRules: ["Prioritize platform reliability, tenant isolation, API contracts, and product analytics."]
  },
  {
    name: "Financial Services",
    dataTypes: ["trades", "positions", "portfolio data", "market data", "client accounts"],
    systems: ["portfolio management", "trade capture", "risk analytics", "reporting", "settlement"],
    compliance: ["FINRA", "SEC", "SOX"],
    prioritySignals: ["trading", "portfolio", "market data", "positions", "risk"],
    generationRules: ["Use reconciliation, risk, reporting, and regulated workflow context."]
  },
  {
    name: "Ecommerce",
    dataTypes: ["cart events", "orders", "payments", "catalog items", "shipments"],
    systems: ["checkout", "catalog", "fulfillment", "recommendations", "returns"],
    compliance: ["PCI DSS", "CCPA"],
    prioritySignals: ["checkout", "cart", "catalog", "fulfillment", "orders"],
    generationRules: ["Focus on conversion-sensitive flows, order accuracy, and catalog availability."]
  },
  {
    name: "Logistics",
    dataTypes: ["shipments", "routes", "fleet telemetry", "warehouse events", "delivery scans"],
    systems: ["transportation management", "warehouse management", "route optimization", "tracking portals"],
    compliance: ["DOT", "SOC2"],
    prioritySignals: ["shipment", "route", "fleet", "warehouse", "delivery"],
    generationRules: ["Connect work to route visibility, delivery accuracy, and warehouse throughput."]
  },
  {
    name: "Supply Chain",
    dataTypes: ["supplier records", "purchase orders", "inventory positions", "demand forecasts", "shipments"],
    systems: ["procurement", "demand planning", "inventory optimization", "supplier management"],
    compliance: ["SOX", "ISO 9001"],
    prioritySignals: ["supplier", "procurement", "inventory", "demand", "supply chain"],
    generationRules: ["Prefer procurement, demand, inventory, and supplier performance context."]
  }
];

export const TECHNOLOGY_TIMELINES: TechnologyTimeline[] = [
  { name: "Java", validFrom: 1996, validTo: 2035, aliases: ["java"], category: "language", maturityNote: "Enterprise-mainstream since late 1990s." },
  { name: "Spring Boot", validFrom: 2014, validTo: 2035, aliases: ["spring boot"], category: "framework", maturityNote: "Realistic for production adoption from 2015 onward." },
  { name: "React", validFrom: 2013, validTo: 2035, aliases: ["react", "react.js", "reactjs"], category: "frontend", maturityNote: "Production adoption became common after 2014." },
  { name: "Angular", validFrom: 2016, validTo: 2035, aliases: ["angular"], category: "frontend", maturityNote: "Modern Angular starts in 2016." },
  { name: "AngularJS", validFrom: 2010, validTo: 2022, aliases: ["angularjs", "angular.js"], category: "frontend", maturityNote: "Legacy framework; avoid for recent greenfield work." },
  { name: "Node.js", validFrom: 2009, validTo: 2035, aliases: ["node", "node.js", "nodejs"], category: "runtime", maturityNote: "Widely used in production from early 2010s onward." },
  { name: "TypeScript", validFrom: 2012, validTo: 2035, aliases: ["typescript", "ts"], category: "language", maturityNote: "Common in frontend and Node stacks after 2016." },
  { name: "Python", validFrom: 1991, validTo: 2035, aliases: ["python"], category: "language", maturityNote: "Stable across data, backend, and automation roles." },
  { name: "AWS", validFrom: 2006, validTo: 2035, aliases: ["aws", "amazon web services"], category: "cloud", maturityNote: "Enterprise adoption grew strongly after 2010." },
  { name: "Azure", validFrom: 2010, validTo: 2035, aliases: ["azure", "microsoft azure"], category: "cloud", maturityNote: "Realistic after 2011, especially Microsoft enterprises." },
  { name: "GCP", validFrom: 2011, validTo: 2035, aliases: ["gcp", "google cloud"], category: "cloud", maturityNote: "Broad enterprise use grew after mid-2010s." },
  { name: "Docker", validFrom: 2013, validTo: 2035, aliases: ["docker"], category: "platform", maturityNote: "Production usage common after 2015." },
  { name: "Kubernetes", validFrom: 2015, validTo: 2035, aliases: ["kubernetes", "k8s"], category: "platform", maturityNote: "Production usage became common after 2017." },
  { name: "Terraform", validFrom: 2014, validTo: 2035, aliases: ["terraform"], category: "devops", maturityNote: "Common infrastructure-as-code after 2016." },
  { name: "Apache Kafka", validFrom: 2011, validTo: 2035, aliases: ["kafka", "apache kafka", "confluent"], category: "streaming", maturityNote: "Realistic for event streaming after 2013." },
  { name: "Apache Spark", validFrom: 2014, validTo: 2035, aliases: ["spark", "apache spark", "pyspark"], category: "data", maturityNote: "Realistic for production big data after 2015." },
  { name: "Airflow", validFrom: 2015, validTo: 2035, aliases: ["airflow", "apache airflow"], category: "orchestration", maturityNote: "Common workflow orchestration after 2017." },
  { name: "Snowflake", validFrom: 2015, validTo: 2035, aliases: ["snowflake"], category: "warehouse", maturityNote: "Enterprise data platform adoption grew after 2017." },
  { name: "Databricks", validFrom: 2015, validTo: 2035, aliases: ["databricks", "delta lake"], category: "data", maturityNote: "Common lakehouse use after 2018." },
  { name: "Microsoft Fabric", validFrom: 2023, validTo: 2035, aliases: ["fabric", "microsoft fabric"], category: "analytics", maturityNote: "Do not use in roles before 2023." },
  { name: "LangChain", validFrom: 2022, validTo: 2035, aliases: ["langchain"], category: "ai", maturityNote: "Avoid before late 2022." },
  { name: "OpenAI API", validFrom: 2020, validTo: 2035, aliases: ["openai", "openai api", "gpt"], category: "ai", maturityNote: "Generative AI resume claims should mostly appear after 2022." },
  { name: "Salesforce", validFrom: 1999, validTo: 2035, aliases: ["salesforce", "apex", "lightning"], category: "crm", maturityNote: "Long-running enterprise CRM stack." },
  { name: "Selenium", validFrom: 2004, validTo: 2035, aliases: ["selenium", "webdriver"], category: "testing", maturityNote: "Common automation framework for many timelines." },
  { name: "Playwright", validFrom: 2020, validTo: 2035, aliases: ["playwright"], category: "testing", maturityNote: "Avoid before 2020." },
  { name: "Cypress", validFrom: 2017, validTo: 2035, aliases: ["cypress"], category: "testing", maturityNote: "Common frontend testing after 2018." },
  { name: "Hadoop", validFrom: 2006, validTo: 2030, aliases: ["hadoop", "hdfs", "hive"], category: "data", maturityNote: "Older big data stack; lower freshness after 2020." }
];

export const SKILL_TAXONOMY: Record<string, string[]> = {
  "Apache Kafka": ["kafka", "apache kafka", "confluent kafka", "kafka streams"],
  "Apache Spark": ["spark", "apache spark", "pyspark", "spark streaming"],
  "AWS": ["aws", "lambda", "s3", "ecs", "eks", "rds", "cloudwatch"],
  "Azure": ["azure", "azure devops", "azure functions", "synapse", "adls"],
  "React": ["react", "react.js", "reactjs"],
  "Spring Boot": ["spring boot", "springboot"],
  "PostgreSQL": ["postgres", "postgresql", "pgvector"],
  "Snowflake": ["snowflake"],
  "Terraform": ["terraform", "iac", "infrastructure as code"],
  "Kubernetes": ["kubernetes", "k8s"],
  "Docker": ["docker", "containers"],
  "TypeScript": ["typescript", "ts"],
  "Python": ["python", "fastapi", "django", "flask"],
  "Selenium": ["selenium", "webdriver"],
  "Playwright": ["playwright"],
  "Salesforce": ["salesforce", "apex", "lightning"]
};

export const INTELLIGENCE_COMPONENTS: ResumeComponent[] = [
  {
    id: "cmp-data-banking-lineage-001",
    role: "Data Engineer",
    technology: "Apache Spark",
    domain: "Banking",
    timelineStart: 2017,
    timelineEnd: 2035,
    componentType: "responsibility",
    intent: "payment lineage controls",
    baseLogic: "Built Spark validation jobs for payment feeds and ledger extracts to identify missing fields before downstream reconciliation cycles.",
    variations: [
      "Built Spark validation jobs for payment feeds and ledger extracts, catching missing fields before downstream reconciliation cycles began.",
      "Implemented Spark quality checks across payment and ledger feeds, reducing reconciliation defects before files reached reporting pipelines.",
      "Created Spark-based validation rules for payment feeds, ledger extracts, and exception files so finance teams received cleaner daily data."
    ],
    qualityScore: 94,
    usageCount: 318,
    freshnessScore: 92,
    deprecationScore: 3,
    status: "published",
    tags: ["lineage", "payments", "spark", "reconciliation"],
    approvedBy: "admin"
  },
  {
    id: "cmp-data-banking-kafka-fraud-001",
    role: "Data Engineer",
    technology: "Apache Kafka",
    domain: "Banking",
    timelineStart: 2016,
    timelineEnd: 2035,
    componentType: "responsibility",
    intent: "fraud event streaming",
    baseLogic: "Processed card and payment events through Kafka topics so fraud monitoring teams received cleaner near-real-time transaction signals.",
    variations: [
      "Processed card and payment events through Kafka topics so fraud monitoring teams received cleaner near-real-time transaction signals.",
      "Maintained Kafka streams for card, payment, and exception events, improving the reliability of fraud monitoring inputs.",
      "Routed payment and card events through Kafka with schema checks so fraud analysts could review cleaner transaction signals."
    ],
    qualityScore: 92,
    usageCount: 271,
    freshnessScore: 94,
    deprecationScore: 2,
    status: "published",
    tags: ["fraud", "payments", "kafka", "transaction monitoring"],
    approvedBy: "admin"
  },
  {
    id: "cmp-data-banking-airflow-audit-001",
    role: "Data Engineer",
    technology: "Airflow",
    domain: "Banking",
    timelineStart: 2017,
    timelineEnd: 2035,
    componentType: "responsibility",
    intent: "audit-ready orchestration",
    baseLogic: "Orchestrated payment and ledger jobs in Airflow with retry paths, dependency checks, and run history for audit review.",
    variations: [
      "Orchestrated payment and ledger jobs in Airflow with retry paths, dependency checks, and run history for audit review.",
      "Managed Airflow schedules for payment, ledger, and exception feeds, keeping run history visible for control reviews.",
      "Configured Airflow dependencies and retry handling for banking data jobs so failed payment feeds were easier to trace."
    ],
    qualityScore: 90,
    usageCount: 199,
    freshnessScore: 91,
    deprecationScore: 2,
    status: "published",
    tags: ["airflow", "audit", "payments", "ledger"],
    approvedBy: "admin"
  },
  {
    id: "cmp-data-banking-postgres-lineage-001",
    role: "Data Engineer",
    technology: "PostgreSQL",
    domain: "Banking",
    timelineStart: 2012,
    timelineEnd: 2035,
    componentType: "responsibility",
    intent: "lineage metadata capture",
    baseLogic: "Captured source-to-target lineage in PostgreSQL tables so analysts could trace payment fields used in regulatory reports.",
    variations: [
      "Captured source-to-target lineage in PostgreSQL tables so analysts could trace payment fields used in regulatory reports.",
      "Maintained PostgreSQL lineage tables for payment attributes, helping reporting teams verify source fields during audit requests.",
      "Documented payment field movement in PostgreSQL metadata tables so regulatory reporting teams could validate source mappings."
    ],
    qualityScore: 88,
    usageCount: 154,
    freshnessScore: 87,
    deprecationScore: 1,
    status: "published",
    tags: ["postgresql", "lineage", "regulatory reporting", "payments"],
    approvedBy: "admin"
  },
  {
    id: "cmp-data-banking-aws-controls-001",
    role: "AWS Data Engineer",
    technology: "AWS",
    domain: "Banking",
    timelineStart: 2015,
    timelineEnd: 2035,
    componentType: "environment",
    intent: "controlled banking data lake",
    baseLogic: "Maintained AWS storage, access policies, and logging controls for banking data feeds used by payment reporting teams.",
    variations: [
      "Maintained AWS storage, access policies, and logging controls for banking data feeds used by payment reporting teams.",
      "Configured AWS data lake controls across storage, access policies, and logs for regulated payment reporting feeds.",
      "Supported AWS data storage and audit logging controls so banking reporting feeds remained traceable and access-reviewed."
    ],
    qualityScore: 91,
    usageCount: 212,
    freshnessScore: 93,
    deprecationScore: 1,
    status: "published",
    tags: ["aws", "data lake", "audit logging", "payments"],
    approvedBy: "admin"
  },
  {
    id: "cmp-data-banking-quality-achievement-001",
    role: "Data Engineer",
    technology: "SQL",
    domain: "Banking",
    timelineStart: 2008,
    timelineEnd: 2035,
    componentType: "achievement",
    intent: "payment data quality improvement",
    baseLogic: "Improved payment data quality checks by separating rejected records, late files, and mapping issues before daily reconciliation reviews.",
    variations: [
      "Improved payment data quality checks by separating rejected records, late files, and mapping issues before daily reconciliation reviews.",
      "Reduced reconciliation review effort by isolating rejected payment records, late files, and mapping issues in daily quality outputs.",
      "Clarified payment data quality reporting by splitting rejected records, late-arriving files, and mapping issues for finance review."
    ],
    qualityScore: 93,
    usageCount: 266,
    freshnessScore: 88,
    deprecationScore: 1,
    status: "published",
    tags: ["data quality", "payments", "reconciliation", "sql"],
    approvedBy: "admin"
  },
  {
    id: "cmp-data-healthcare-eligibility-001",
    role: "Data Engineer",
    technology: "Apache Kafka",
    domain: "Healthcare",
    timelineStart: 2016,
    timelineEnd: 2035,
    componentType: "responsibility",
    intent: "eligibility event processing",
    baseLogic: "Streamed eligibility updates through Kafka topics and downstream data marts to keep member coverage changes visible to claims systems.",
    variations: [
      "Streamed eligibility updates through Kafka topics and curated marts, keeping member coverage changes visible to claims processing teams.",
      "Routed member eligibility events through Kafka and batch reconciliation checks so claims systems received timely coverage updates.",
      "Maintained Kafka pipelines for eligibility updates, provider changes, and coverage corrections to reduce delays in claims adjudication."
    ],
    qualityScore: 91,
    usageCount: 241,
    freshnessScore: 90,
    deprecationScore: 2,
    status: "published",
    tags: ["healthcare", "eligibility", "kafka", "claims"],
    approvedBy: "admin"
  },
  {
    id: "cmp-data-retail-inventory-001",
    role: "Data Engineer",
    technology: "Snowflake",
    domain: "Retail",
    timelineStart: 2018,
    timelineEnd: 2035,
    componentType: "achievement",
    intent: "inventory accuracy",
    baseLogic: "Reworked inventory marts in Snowflake to reconcile store counts, online reservations, and fulfillment exceptions for merchandising teams.",
    variations: [
      "Reworked Snowflake inventory marts to reconcile store counts, online reservations, and fulfillment exceptions for merchandising teams.",
      "Redesigned inventory tables in Snowflake so store counts, reservations, and fulfillment exceptions aligned during daily merchandising reviews.",
      "Improved Snowflake inventory models by separating store counts, reservation holds, and fulfillment exceptions into clearer reporting layers."
    ],
    qualityScore: 89,
    usageCount: 187,
    freshnessScore: 93,
    deprecationScore: 1,
    status: "published",
    tags: ["retail", "inventory", "snowflake", "fulfillment"],
    approvedBy: "admin"
  },
  {
    id: "cmp-java-banking-api-001",
    role: "Java Backend Engineer",
    technology: "Spring Boot",
    domain: "Banking",
    timelineStart: 2015,
    timelineEnd: 2035,
    componentType: "responsibility",
    intent: "payment API reliability",
    baseLogic: "Developed Spring Boot APIs for payment status lookups with validation, retries, and audit logging for branch support workflows.",
    variations: [
      "Developed Spring Boot APIs for payment status lookups, adding validation, retries, and audit logging for branch support workflows.",
      "Built payment status services in Spring Boot with request validation, retry handling, and audit logs for branch servicing teams.",
      "Maintained Spring Boot payment lookup endpoints that verified request fields, handled retry paths, and preserved traceable support actions."
    ],
    qualityScore: 93,
    usageCount: 402,
    freshnessScore: 91,
    deprecationScore: 2,
    status: "published",
    tags: ["spring boot", "payments", "api", "audit"],
    approvedBy: "admin"
  },
  {
    id: "cmp-java-retail-checkout-001",
    role: "Java Full Stack Developer",
    technology: "React",
    domain: "Ecommerce",
    timelineStart: 2016,
    timelineEnd: 2035,
    componentType: "responsibility",
    intent: "checkout exception handling",
    baseLogic: "Updated checkout screens and Java services to surface payment failures, tax mismatches, and cart validation errors without blocking support reviews.",
    variations: [
      "Updated checkout screens and Java services to surface payment failures, tax mismatches, and cart validation errors for support reviews.",
      "Enhanced React checkout flows and Java services so payment failures, tax mismatches, and cart errors were visible before order submission.",
      "Reworked checkout exception handling across React and Java APIs, helping support teams inspect payment and cart validation failures faster."
    ],
    qualityScore: 88,
    usageCount: 226,
    freshnessScore: 88,
    deprecationScore: 2,
    status: "published",
    tags: ["ecommerce", "checkout", "react", "java"],
    approvedBy: "admin"
  },
  {
    id: "cmp-devops-tech-observability-001",
    role: "DevOps Engineer",
    technology: "Kubernetes",
    domain: "Technology",
    timelineStart: 2018,
    timelineEnd: 2035,
    componentType: "responsibility",
    intent: "tenant service reliability",
    baseLogic: "Standardized Kubernetes deployment checks and service dashboards to catch failing tenant workloads before customer support escalations increased.",
    variations: [
      "Standardized Kubernetes deployment checks and service dashboards, catching failing tenant workloads before customer support escalations increased.",
      "Improved Kubernetes release checks and observability views so tenant service failures were visible before broad customer impact.",
      "Maintained Kubernetes readiness checks, alerts, and service dashboards to reduce late discovery of tenant workload failures."
    ],
    qualityScore: 90,
    usageCount: 171,
    freshnessScore: 95,
    deprecationScore: 1,
    status: "published",
    tags: ["kubernetes", "observability", "tenant", "reliability"],
    approvedBy: "admin"
  },
  {
    id: "cmp-qa-insurance-claims-001",
    role: "SDET",
    technology: "Selenium",
    domain: "Insurance",
    timelineStart: 2012,
    timelineEnd: 2035,
    componentType: "responsibility",
    intent: "claims regression automation",
    baseLogic: "Automated claims regression scenarios with Selenium and API checks to verify policy rules before monthly release approvals.",
    variations: [
      "Automated claims regression scenarios with Selenium and API checks, verifying policy rules before monthly release approvals.",
      "Built Selenium coverage for claims intake, policy validation, and payment review flows so release teams caught rule defects earlier.",
      "Maintained Selenium regression tests for claims workflows, policy validations, and payment screens to protect monthly release stability."
    ],
    qualityScore: 87,
    usageCount: 289,
    freshnessScore: 81,
    deprecationScore: 8,
    status: "published",
    tags: ["insurance", "selenium", "claims", "regression"],
    approvedBy: "admin"
  },
  {
    id: "cmp-cloud-gov-fedramp-001",
    role: "AWS Cloud Engineer",
    technology: "AWS",
    domain: "Government",
    timelineStart: 2014,
    timelineEnd: 2035,
    componentType: "environment",
    intent: "regulated cloud operations",
    baseLogic: "Supported AWS environments with encrypted storage, controlled access policies, and audit trails for regulated citizen service workloads.",
    variations: [
      "Supported AWS environments with encrypted storage, access policies, and audit trails for regulated citizen service workloads.",
      "Maintained AWS infrastructure controls across storage, IAM, logging, and backup paths for regulated public sector workloads.",
      "Configured AWS operational controls for citizen service applications, including encryption, logging, access reviews, and backup verification."
    ],
    qualityScore: 92,
    usageCount: 133,
    freshnessScore: 94,
    deprecationScore: 1,
    status: "published",
    tags: ["aws", "government", "fedramp", "iam"],
    approvedBy: "admin"
  },
  {
    id: "cmp-salesforce-healthcare-case-001",
    role: "Salesforce Developer",
    technology: "Salesforce",
    domain: "Healthcare",
    timelineStart: 2014,
    timelineEnd: 2035,
    componentType: "responsibility",
    intent: "provider case workflow",
    baseLogic: "Configured Salesforce case workflows and Apex validations to route provider inquiries while preserving PHI-aware field access controls.",
    variations: [
      "Configured Salesforce case workflows and Apex validations to route provider inquiries while preserving PHI-aware field access controls.",
      "Built Salesforce validations and case routing rules for provider inquiries, keeping PHI fields restricted during support reviews.",
      "Maintained Salesforce case flows, Apex checks, and field permissions so provider support teams handled healthcare inquiries securely."
    ],
    qualityScore: 89,
    usageCount: 116,
    freshnessScore: 90,
    deprecationScore: 2,
    status: "published",
    tags: ["salesforce", "healthcare", "case management", "apex"],
    approvedBy: "admin"
  },
  {
    id: "cmp-draft-fabric-legacy-001",
    role: "Data Engineer",
    technology: "Microsoft Fabric",
    domain: "Banking",
    timelineStart: 2018,
    timelineEnd: 2020,
    componentType: "responsibility",
    intent: "legacy fabric migration",
    baseLogic: "Migrated 2018 bank reporting pipelines into Microsoft Fabric workspaces for modern lakehouse governance.",
    variations: [
      "Migrated 2018 bank reporting pipelines into Microsoft Fabric workspaces for modern lakehouse governance."
    ],
    qualityScore: 42,
    usageCount: 0,
    freshnessScore: 12,
    deprecationScore: 91,
    status: "similarity_scan",
    tags: ["invalid timeline", "fabric", "banking"]
  }
];

export const JOB_LISTINGS: JobListing[] = [
  {
    id: "job-001",
    source: "Dice",
    title: "Senior Data Engineer",
    company: "Northbridge Bank",
    location: "Charlotte, NC",
    domain: "Banking",
    skills: ["Apache Spark", "Apache Kafka", "AWS", "SQL", "Data Lineage"],
    normalizedScore: 94,
    postedAt: "2026-05-09",
    applyMode: "human_assisted"
  },
  {
    id: "job-002",
    source: "LinkedIn",
    title: "Java Backend Engineer",
    company: "Cedar Payments",
    location: "Remote",
    domain: "Financial Services",
    skills: ["Java", "Spring Boot", "Kafka", "PostgreSQL", "AWS"],
    normalizedScore: 91,
    postedAt: "2026-05-08",
    applyMode: "connector_ready"
  },
  {
    id: "job-003",
    source: "Prime Vendor",
    title: "SDET Automation Engineer",
    company: "Everwell Insurance",
    location: "Hartford, CT",
    domain: "Insurance",
    skills: ["Selenium", "REST Assured", "Java", "CI/CD"],
    normalizedScore: 88,
    postedAt: "2026-05-07",
    applyMode: "manual"
  },
  {
    id: "job-004",
    source: "ZipRecruiter",
    title: "AWS Cloud Engineer",
    company: "CivicPath Systems",
    location: "Arlington, VA",
    domain: "Government",
    skills: ["AWS", "Terraform", "IAM", "CloudWatch", "FedRAMP"],
    normalizedScore: 86,
    postedAt: "2026-05-06",
    applyMode: "human_assisted"
  }
];

export const APPLICATIONS: ApplicationRecord[] = [
  {
    id: "app-001",
    jobId: "job-001",
    userId: "user-demo",
    resumeId: "resume-bank-data-v3",
    status: "Interview Scheduled",
    atsScore: 92,
    realismScore: 88,
    appliedAt: "2026-05-04",
    artifacts: {
      resumeDocx: "s3://lp-demo/resume-bank-data-v3.docx",
      jdSnapshot: "s3://lp-demo/job-001-jd.txt",
      coverLetter: "s3://lp-demo/job-001-cover.txt"
    }
  },
  {
    id: "app-002",
    jobId: "job-002",
    userId: "user-demo",
    resumeId: "resume-java-payments-v2",
    status: "Recruiter Viewed",
    atsScore: 89,
    realismScore: 91,
    appliedAt: "2026-05-05",
    artifacts: {
      resumeDocx: "s3://lp-demo/resume-java-payments-v2.docx",
      jdSnapshot: "s3://lp-demo/job-002-jd.txt",
      coverLetter: "s3://lp-demo/job-002-cover.txt"
    }
  }
];

export const PROMPT_VERSIONS: PromptVersion[] = [
  {
    id: "prompt-v3",
    name: "Domain Timeline Validator",
    modelRoute: "Complex generation to GPT-5.4, lightweight rewrites to compact model, reviewer pass to Claude",
    status: "active",
    averageAtsScore: 91,
    averageRealismScore: 88,
    callbackRate: 18.4
  },
  {
    id: "prompt-v2",
    name: "Human Naturalness Rewrite",
    modelRoute: "Primary generation plus reviewer pass",
    status: "testing",
    averageAtsScore: 87,
    averageRealismScore: 92,
    callbackRate: 16.1
  },
  {
    id: "prompt-v1",
    name: "ATS Coverage Baseline",
    modelRoute: "Single model full generation",
    status: "retired",
    averageAtsScore: 82,
    averageRealismScore: 71,
    callbackRate: 9.8
  }
];

export const AUDIT_EVENTS: AuditEvent[] = [
  {
    id: "audit-001",
    actor: "admin@askmehire.com",
    action: "Published component cmp-java-banking-api-001",
    entity: "ResumeComponent",
    timestamp: "2026-05-10T12:18:00Z",
    severity: "info"
  },
  {
    id: "audit-002",
    actor: "system",
    action: "Blocked Microsoft Fabric component for invalid 2018 timeline",
    entity: "TimelineValidation",
    timestamp: "2026-05-10T13:44:00Z",
    severity: "warning"
  },
  {
    id: "audit-003",
    actor: "reviewer@askmehire.com",
    action: "Requested rewrite for duplicate claims automation wording",
    entity: "ApprovalWorkflow",
    timestamp: "2026-05-10T15:02:00Z",
    severity: "info"
  }
];
